# Server configuration
server:
  port: 8099                   # The gateway will run on port 8099

spring:
  application:
    name: gateway              # Human-friendly name of the gateway


  data:
    mongodb:
      uri: mongodb+srv://trung:admin@gateway.1gud6jr.mongodb.net/?retryWrites=true&w=majority]
      database: gateway_routes

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL cá»§a Eureka Server
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost


# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Debug-level logs for the gateway
    org.springframework.data.mongodb: DEBUG  # MongoDB debug logs

# Spring Boot Actuator for health checks, refresh endpoints, etc.
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info